name: agents-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pandas
  - flask
  - spotipy
  - pip:
    - langgraph
    - langchain-google-genai
    - langchain-core
    - geopy
    - requests
    - sqlparse
    - pydantic
